### ISSUE TITLE
assert error when creating tab bar

### ISSUE THREAD

**Issue by nnop** [pthom/imgui_bundle#108]
Thanks for your work. I'm testing imgui functions and met the following error when creating tab bar and tab items.

```python
from imgui_bundle import imgui, immapp, hello_imgui

def show_gui():
    if imgui.is_key_pressed(imgui.Key.escape):
        runner_params.app_shall_exit = True

    if imgui.begin_tab_bar('###tabs', imgui.TabBarFlags_.none):
        if imgui.begin_tab_item('sizes'):
            imgui.text('sizes')
            imgui.end_tab_item()
        if imgui.begin_tab_item('colors'):
            imgui.text('colors')
            imgui.end_tab_item()
        imgui.end_tab_bar()
    
if __name__ == "__main__":
    runner_params = hello_imgui.RunnerParams()
    runner_params.callbacks.show_gui = show_gui
    immapp.run(runner_params=runner_params)
```

assert error:
```bash
Traceback (most recent call last):
  File "gui.py", line 26, in <module>
    immapp.run(runner_params=runner_params)
  File "gui.py", line 21, in show_gui
    imgui.end_tab_bar()
RuntimeError: IM_ASSERT( window->IDStack.Size > 1 )   ---   imgui.cpp:8170
```

The code is ported according to codes in `imgui_demo.cpp`:
![image](https://github.com/pthom/imgui_bundle/assets/23091984/68985d23-0b12-4685-83ba-187dcdf44a44)

**Comment by pthom** [comment]
Hi,

Thank for your message and kind words.

Here is the python signature for `begin_tab_item`
```python
# IMGUI_API bool          BeginTabItem(const char* label, bool* p_open = NULL, ImGuiTabItemFlags flags = 0);     /* original C++ signature */
def begin_tab_item(
    label: str, p_open: Optional[bool] = None, flags: TabItemFlags = 0
) -> Tuple[bool, Optional[bool]]:
    """create a Tab. Returns True if the Tab is selected."""
    pass

```

As you see, it returns a `Tuple[bool, Optional[bool]]`. This is a bit tricky, I agree. However this is due to the fact that the API translation is automatic, and the C++ signature allow for a modifiable boolean parameter (`p_open`).

To solve your issue you need to query only the first value from the tuple returned by `begin_tab_item`:

```python
    if imgui.begin_tab_bar('###tabs', imgui.TabBarFlags_.none):

        # either you get both output values from begin_tab_items
        opened, _ = imgui.begin_tab_item('sizes')
        if opened:
            imgui.text('sizes')
            imgui.end_tab_item()

        # Or, you just query the first output result
        if imgui.begin_tab_item('colors')[0]:
            imgui.text('colors')
            imgui.end_tab_item()
        imgui.end_tab_bar()

```
