### ISSUE TITLE
Installation fails on python 3.12 (pre-release)

### ISSUE THREAD

**Issue by shenef** [pthom/imgui_bundle#130]
Initially i ran into PyGLM failing to install but after seeing it's apparently only used in one imgui-bundle demo, i tried removing it from setup.py but now building wheels for imgui-bundle fails.
(maybe because i removed it, i'm not familiar with building packages)
Python version: 3.12.0rc3
<details><summary>Log:</summary>
<p>

```
PS E:\SoS-TAS> pip install git+https://github.com/shenef/imgui_bundle.git
Collecting git+https://github.com/shenef/imgui_bundle.git
  Cloning https://github.com/shenef/imgui_bundle.git to c:\users\shen\appdata\local\temp\pip-req-build-b8604ehv
  Running command git clone --filter=blob:none --quiet https://github.com/shenef/imgui_bundle.git 'C:\Users\shen\AppData\Local\Temp\pip-req-build-b8604ehv'
  Resolved https://github.com/shenef/imgui_bundle.git to commit 37380db6c53953f6807e27e5713aff1389b140dd
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.15 in c:\users\shen\appdata\local\programs\python\python312\lib\site-packages (from imgui-bundle==0.8.8) (1.26.0rc1)
Collecting munch>=2.0.0 (from imgui-bundle==0.8.8)
  Obtaining dependency information for munch>=2.0.0 from https://files.pythonhosted.org/packages/56/b3/7c69b37f03260a061883bec0e7b05be7117c1b1c85f5212c72c8c2bc3c8c/munch-4.0.0-py2.py3-none-any.whl.metadata
  Using cached munch-4.0.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: glfw>2.5 in c:\users\shen\appdata\local\programs\python\python312\lib\site-packages (from imgui-bundle==0.8.8) (2.6.2)
Requirement already satisfied: PyOpenGL>=3.0 in c:\users\shen\appdata\local\programs\python\python312\lib\site-packages (from imgui-bundle==0.8.8) (3.1.7)
Collecting pillow>=9.0.0 (from imgui-bundle==0.8.8)
  Obtaining dependency information for pillow>=9.0.0 from https://files.pythonhosted.org/packages/00/00/d42abea0b4a415ea1e0975c981f95f354de1280d7e7bef3882bf1464b795/Pillow-10.0.1-cp312-cp312-win_amd64.whl.metadata
  Downloading Pillow-10.0.1-cp312-cp312-win_amd64.whl.metadata (9.6 kB)
Downloading munch-4.0.0-py2.py3-none-any.whl (9.9 kB)
Downloading Pillow-10.0.1-cp312-cp312-win_amd64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 7.6 MB/s eta 0:00:00
Building wheels for collected packages: imgui-bundle
  Building wheel for imgui-bundle (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for imgui-bundle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [355 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- The C compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.36.32535.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (2.8s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/shen/AppData/Local/Temp/pip-req-build-b8604ehv/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\shen\AppData\Local\Temp\pip-req-build-b8604ehv\_skbuild\win-amd64-3.12\cmake-build
        Command:
          'C:\Users\shen\AppData\Local\Temp\pip-build-env-j79e7p0d\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\shen\AppData\Local\Temp\pip-req-build-b8604ehv' -G Ninja -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\shen\AppData\Local\Temp\pip-req-build-b8604ehv\_skbuild\win-amd64-3.12\cmake-install\bindings\imgui_bundle' -DPYTHON_VERSION_STRING:STRING=3.12.0rc3 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\shen\AppData\Local\Temp\pip-build-env-j79e7p0d\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\libs\python312.lib' '-DPython_EXECUTABLE:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\Include' '-DPython_LIBRARY:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\libs\python312.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\Include' '-DPython3_LIBRARY:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\libs\python312.lib' -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.36.32535.0
      -- The CXX compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      'C:/Users/shen/AppData/Local/Programs/Python/Python312/python.exe' '-c' 'import pybind11; print(pybind11.get_cmake_dir())'
      CMake Warning (dev) at C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/pybind11/share/cmake/pybind11/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/pybind11/share/cmake/pybind11/pybind11Tools.cmake:50 (find_package)
        C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/pybind11/share/cmake/pybind11/pybind11Common.cmake:188 (include)
        C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/pybind11/share/cmake/pybind11/pybind11Config.cmake:250 (include)
        cmake/find_pybind11.cmake:20 (find_package)
        CMakeLists.txt:132 (find_pybind11)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonInterp: C:/Users/shen/AppData/Local/Programs/Python/Python312/python.exe (found suitable version "3.12", minimum required is "3.6")
      -- Found PythonLibs: C:/Users/shen/AppData/Local/Programs/Python/Python312/libs/python312.lib
      -- Performing Test HAS_MSVC_GL_LTCG
      -- Performing Test HAS_MSVC_GL_LTCG - Success
      -- Found pybind11: C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/pybind11/include (found version "2.11.1")
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - not found
      -- Found Threads: TRUE
      -- Using Win32 for window creation
      CMake Deprecation Warning at external/SDL/SDL/CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
      -- Looking for __GLIBC__
      -- Looking for __GLIBC__ - not found
      -- Looking for immintrin.h
      -- Looking for immintrin.h - found
      -- Looking for stdint.h
      -- Looking for stdint.h - found
      -- Performing Test HAVE_WIN32_CC
      -- Performing Test HAVE_WIN32_CC - Success
      -- Looking for d3d9.h
      -- Looking for d3d9.h - found
      -- Looking for d3d11_1.h
      -- Looking for d3d11_1.h - found
      -- Performing Test HAVE_D3D12_H
      -- Performing Test HAVE_D3D12_H - Success
      -- Looking for ddraw.h
      -- Looking for ddraw.h - found
      -- Looking for dsound.h
      -- Looking for dsound.h - found
      -- Looking for dinput.h
      -- Looking for dinput.h - found
      -- Looking for dxgi.h
      -- Looking for dxgi.h - found
      -- Performing Test HAVE_XINPUT_H
      -- Performing Test HAVE_XINPUT_H - Success
      -- Performing Test HAVE_XINPUT_GAMEPAD_EX
      -- Performing Test HAVE_XINPUT_GAMEPAD_EX - Failed
      -- Performing Test HAVE_XINPUT_STATE_EX
      -- Performing Test HAVE_XINPUT_STATE_EX - Failed
      -- Performing Test HAVE_WINDOWS_GAMING_INPUT_H
      -- Performing Test HAVE_WINDOWS_GAMING_INPUT_H - Success
      -- Looking for tpcshrd.h
      -- Looking for tpcshrd.h - found
      -- Looking for roapi.h
      -- Looking for roapi.h - found
      -- Looking for mmdeviceapi.h
      -- Looking for mmdeviceapi.h - found
      -- Looking for audioclient.h
      -- Looking for audioclient.h - found
      -- Looking for sensorsapi.h
      -- Looking for sensorsapi.h - found
      -- Looking for shellscalingapi.h
      -- Looking for shellscalingapi.h - found
      -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.41.0.windows.2")
      CMake Deprecation Warning at external/SDL/SDL/CMakeLists.txt:3143 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      --
      -- SDL2 was configured with the following options:
      --
      -- Platform: Windows-10.0.22631
      -- 64-bit:   TRUE
      -- Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe
      -- Revision: SDL-release-2.26.1-11-gd992d4f23
      --
      -- Subsystems:
      --   Atomic:        ON
      --   Audio: ON
      --   Video: ON
      --   Render:        ON
      --   Events:        ON
      --   Joystick:      ON
      --   Haptic:        ON
      --   Hidapi:        ON
      --   Power: ON
      --   Threads:       ON
      --   Timers:        ON
      --   File:  ON
      --   Loadso:        ON
      --   CPUinfo:       ON
      --   Filesystem:    ON
      --   Sensor:        ON
      --   Locale:        ON
      --   Misc:  ON
      --
      -- Options:
      --   SDL2_DISABLE_INSTALL        (Wanted: ON): OFF
      --   SDL2_DISABLE_SDL2MAIN       (Wanted: OFF): OFF
      --   SDL2_DISABLE_UNINSTALL      (Wanted: OFF): OFF
      --   SDL_3DNOW                   (Wanted: ON): OFF
      --   SDL_ALSA                    (Wanted: OFF): OFF
      --   SDL_ALSA_SHARED             (Wanted: OFF): OFF
      --   SDL_ALTIVEC                 (Wanted: ON): OFF
      --   SDL_ARMNEON                 (Wanted: OFF): OFF
      --   SDL_ARMSIMD                 (Wanted: OFF): OFF
      --   SDL_ARTS                    (Wanted: OFF): OFF
      --   SDL_ARTS_SHARED             (Wanted: OFF): OFF
      --   SDL_ASAN                    (Wanted: OFF): OFF
      --   SDL_ASSEMBLY                (Wanted: ON): OFF
      --   SDL_ASSERTIONS              (Wanted: auto): auto
      --   SDL_BACKGROUNDING_SIGNAL    (Wanted: OFF): OFF
      --   SDL_CCACHE                  (Wanted: ON): OFF
      --   SDL_CLOCK_GETTIME           (Wanted: OFF): OFF
      --   SDL_COCOA                   (Wanted: OFF): OFF
      --   SDL_DBUS                    (Wanted: OFF): OFF
      --   SDL_DIRECTFB                (Wanted: OFF): OFF
      --   SDL_DIRECTFB_SHARED         (Wanted: OFF): OFF
      --   SDL_DIRECTX                 (Wanted: ON): ON
      --   SDL_DISKAUDIO               (Wanted: ON): ON
      --   SDL_DUMMYAUDIO              (Wanted: ON): ON
      --   SDL_DUMMYVIDEO              (Wanted: ON): ON
      --   SDL_ESD                     (Wanted: OFF): OFF
      --   SDL_ESD_SHARED              (Wanted: OFF): OFF
      --   SDL_FOREGROUNDING_SIGNAL    (Wanted: OFF): OFF
      --   SDL_FUSIONSOUND             (Wanted: OFF): OFF
      --   SDL_FUSIONSOUND_SHARED      (Wanted: OFF): OFF
      --   SDL_GCC_ATOMICS             (Wanted: OFF): OFF
      --   SDL_HIDAPI                  (Wanted: ON): ON
      --   SDL_HIDAPI_JOYSTICK         (Wanted: ON): ON
      --   SDL_HIDAPI_LIBUSB           (Wanted: OFF): OFF
      --   SDL_IBUS                    (Wanted: OFF): OFF
      --   SDL_INSTALL_TESTS           (Wanted: OFF): OFF
      --   SDL_JACK                    (Wanted: OFF): OFF
      --   SDL_JACK_SHARED             (Wanted: OFF): OFF
      --   SDL_KMSDRM                  (Wanted: OFF): OFF
      --   SDL_KMSDRM_SHARED           (Wanted: OFF): OFF
      --   SDL_LIBC                    (Wanted: OFF): OFF
      --   SDL_LIBSAMPLERATE           (Wanted: OFF): OFF
      --   SDL_LIBSAMPLERATE_SHARED    (Wanted: OFF): OFF
      --   SDL_METAL                   (Wanted: OFF): OFF
      --   SDL_MMX                     (Wanted: ON): OFF
      --   SDL_NAS                     (Wanted: OFF): OFF
      --   SDL_NAS_SHARED              (Wanted: OFF): OFF
      --   SDL_OFFSCREEN               (Wanted: ON): ON
      --   SDL_OPENGL                  (Wanted: ON): ON
      --   SDL_OPENGLES                (Wanted: ON): ON
      --   SDL_OSS                     (Wanted: OFF): OFF
      --   SDL_PIPEWIRE                (Wanted: OFF): OFF
      --   SDL_PIPEWIRE_SHARED         (Wanted: OFF): OFF
      --   SDL_PTHREADS                (Wanted: OFF): OFF
      --   SDL_PTHREADS_SEM            (Wanted: OFF): OFF
      --   SDL_PULSEAUDIO              (Wanted: OFF): OFF
      --   SDL_PULSEAUDIO_SHARED       (Wanted: OFF): OFF
      --   SDL_RENDER_D3D              (Wanted: ON): ON
      --   SDL_RENDER_METAL            (Wanted: OFF): OFF
      --   SDL_RPATH                   (Wanted: OFF): OFF
      --   SDL_RPI                     (Wanted: OFF): OFF
      --   SDL_SNDIO                   (Wanted: OFF): OFF
      --   SDL_SNDIO_SHARED            (Wanted: OFF): OFF
      --   SDL_SSE                     (Wanted: ON): ON
      --   SDL_SSE2                    (Wanted: ON): ON
      --   SDL_SSE3                    (Wanted: ON): ON
      --   SDL_SSEMATH                 (Wanted: ON): OFF
      --   SDL_STATIC_PIC              (Wanted: OFF): OFF
      --   SDL_SYSTEM_ICONV            (Wanted: ON): OFF
      --   SDL_TESTS                   (Wanted: OFF): OFF
      --   SDL_VENDOR_INFO             (Wanted: ): OFF
      --   SDL_VIRTUAL_JOYSTICK        (Wanted: ON): ON
      --   SDL_VIVANTE                 (Wanted: OFF): OFF
      --   SDL_VULKAN                  (Wanted: ON): ON
      --   SDL_WASAPI                  (Wanted: ON): ON
      --   SDL_WAYLAND                 (Wanted: OFF): OFF
      --   SDL_WAYLAND_LIBDECOR        (Wanted: OFF): OFF
      --   SDL_WAYLAND_LIBDECOR_SHARED (Wanted: OFF): OFF
      --   SDL_WAYLAND_QT_TOUCH        (Wanted: OFF): OFF
      --   SDL_WAYLAND_SHARED          (Wanted: OFF): OFF
      --   SDL_X11                     (Wanted: OFF): OFF
      --   SDL_X11_SHARED              (Wanted: OFF): OFF
      --   SDL_X11_XCURSOR             (Wanted: OFF): OFF
      --   SDL_X11_XDBE                (Wanted: OFF): OFF
      --   SDL_X11_XFIXES              (Wanted: OFF): OFF
      --   SDL_X11_XINPUT              (Wanted: OFF): OFF
      --   SDL_X11_XRANDR              (Wanted: OFF): OFF
      --   SDL_X11_XSCRNSAVER          (Wanted: OFF): OFF
      --   SDL_X11_XSHAPE              (Wanted: OFF): OFF
      --   SDL_XINPUT                  (Wanted: ON): ON
      --
      --  CFLAGS:        /DWIN32 /D_WINDOWS
      --  EXTRA_CFLAGS:
      --  EXTRA_LDFLAGS:
      --  EXTRA_LIBS:    user32;gdi32;winmm;imm32;ole32;oleaut32;version;uuid;advapi32;setupapi;shell32;dinput8
      --
      --  Build Shared Library: ON
      --  Build Static Library: OFF
      --
      -- Performing Test CHECK_CPU_ARCHITECTURE_X86
      -- Performing Test CHECK_CPU_ARCHITECTURE_X86 - Failed
      ccache not found cannot use
      -- Library hello_imgui
      CMake Warning at external/hello_imgui/hello_imgui/src/hello_imgui/CMakeLists.txt:64 (find_package):
        By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "SDL2", but
        CMake did not find one.

        Could not find a package configuration file provided by "SDL2" with any of
        the following names:

          SDL2Config.cmake
          sdl2-config.cmake

        Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
        "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
        provides a separate development package or SDK, be sure it has been
        installed.
      Call Stack (most recent call first):
        external/hello_imgui/hello_imgui/src/hello_imgui/CMakeLists.txt:86 (link_sdl)


      CMake Warning at external/immvision/immvision/cmake/find_opencv.cmake:216 (find_package):
        By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "OpenCV", but
        CMake did not find one.

        Could not find a package configuration file provided by "OpenCV" with any
        of the following names:

          OpenCVConfig.cmake
          opencv-config.cmake

        Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
        "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
        provides a separate development package or SDK, be sure it has been
        installed.
      Call Stack (most recent call first):
        external/immvision/CMakeLists.txt:2 (immvision_find_opencv)


      FIND OPENCV use immvision_download_opencv_official_package_win
      -- Populating opencv_official_package_win
      -- Configuring done (0.2s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/shen/AppData/Local/Temp/pip-req-build-b8604ehv/_skbuild/win-amd64-3.12/cmake-build/_deps/opencv_official_package_win-subbuild
      ninja: error: Stat(C:/Users/shen/AppData/Local/Temp/pip-req-build-b8604ehv/_skbuild/win-amd64-3.12/cmake-build/_deps/opencv_official_package_win-subbuild/opencv_official_package_win-populate-prefix/src/opencv_official_package_win-populate-stamp/opencv_official_package_win-populate-done): Filename longer than 260 characters
      CMake Error at C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FetchContent.cmake:1662 (message):
        Build step for opencv_official_package_win failed: 1
      Call Stack (most recent call first):
        C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FetchContent.cmake:1802:EVAL:2 (__FetchContent_directPopulate)
        C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FetchContent.cmake:1802 (cmake_language)
        C:/Users/shen/AppData/Local/Temp/pip-build-env-j79e7p0d/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/FetchContent.cmake:2016 (FetchContent_Populate)
        external/immvision/immvision/cmake/find_opencv.cmake:53 (FetchContent_MakeAvailable)
        external/immvision/immvision/cmake/find_opencv.cmake:222 (immvision_download_opencv_official_package_win)
        external/immvision/CMakeLists.txt:2 (immvision_find_opencv)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\shen\AppData\Local\Temp\pip-build-env-j79e7p0d\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "C:\Users\shen\AppData\Local\Temp\pip-build-env-j79e7p0d\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\shen\AppData\Local\Temp\pip-build-env-j79e7p0d\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\shen\AppData\Local\Temp\pip-req-build-b8604ehv' -G Ninja -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\shen\AppData\Loca\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\libs\python312.lib' '-DPython_EXECUTABLE:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\Include' '-DPython_LIBRARY:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\libs\python312.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\Include' '-DPython3_LIBRARY:PATH=C:\Users\shen\AppData\Local\Programs\Python\Python312\libs\python312.lib' -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\shen\AppData\Local\Temp\pip-req-build-b8604ehv
        Working directory:
          C:\Users\shen\AppData\Local\Temp\pip-req-build-b8604ehv\_skbuild\win-amd64-3.12\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for imgui-bundle
Failed to build imgui-bundle
ERROR: Could not build wheels for imgui-bundle, which is required to install pyproject.toml-based projects
```

</p>
</details>

Regarding PyGLM, i already created an issue in their repo.

**Comment by pthom** [comment]
Hi,

The error you are encountering is buried in the log message here:

```
 -- Build files have been written to: C:/Users/shen/AppData/Local/Temp/pip-req-build-b8604ehv/_skbuild/win-amd64-3.12/cmake-build/_deps/opencv_official_package_win-subbuild
      ninja: error: Stat(C:/Users/shen/AppData/Local/Temp/pip-req-build-b8604ehv/_skbuild/win-amd64-3.12/cmake-build/_deps/opencv_official_package_win-subbuild/opencv_official_package_win-populate-prefix/src/opencv_official_package_win-populate-stamp/opencv_official_package_win-populate-done): Filename longer than 260 characters
```

If you scroll to the right, you will read: `Filename longer than 260 characters`

This is a windows related issue (and an annoying one). May be this [stackoverflow answer](https://stackoverflow.com/questions/68351713/maximum-path-lengths-with-cmake) can help. However, I did not test it

**Comment by shenef** [comment]
Thx! I was able to disable the length limit using your suggestion, though unfortunately Ninja needs to be `longPathAware` for that to actually have an effect.
The fix for that has been merged with https://github.com/ninja-build/ninja/pull/2225, though sadly that is not included in their latest release.
In this case I'll just wait for someone to build the wheels or a new Ninja release.

**Comment by pthom** [comment]
I just tried to build the wheels for windows / python 3.12, and it worked on github CI.
Can you test the wheel on your side from the artifacts here: 
https://github.com/pthom/imgui_bundle/actions/runs/6267027251

**Comment by shenef** [comment]
Worked great!
<details><summary>Details</summary>
<p>

```
PS E:\SoS-TAS> pip install imgui_bundle-0.8.8-cp312-cp312-win_amd64.whl
Processing e:\sos-tas\imgui_bundle-0.8.8-cp312-cp312-win_amd64.whl
Requirement already satisfied: numpy>=1.15 in c:\users\shen\appdata\local\programs\python\python312\lib\site-packages (from imgui-bundle==0.8.8) (1.26.0rc1)
Collecting munch>=2.0.0 (from imgui-bundle==0.8.8)
  Obtaining dependency information for munch>=2.0.0 from https://files.pythonhosted.org/packages/56/b3/7c69b37f03260a061883bec0e7b05be7117c1b1c85f5212c72c8c2bc3c8c/munch-4.0.0-py2.py3-none-any.whl.metadata
  Using cached munch-4.0.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: glfw>2.5 in c:\users\shen\appdata\local\programs\python\python312\lib\site-packages (from imgui-bundle==0.8.8) (2.6.2)
Requirement already satisfied: PyOpenGL>=3.0 in c:\users\shen\appdata\local\programs\python\python312\lib\site-packages (from imgui-bundle==0.8.8) (3.1.7)
Collecting pillow>=9.0.0 (from imgui-bundle==0.8.8)
  Obtaining dependency information for pillow>=9.0.0 from https://files.pythonhosted.org/packages/00/00/d42abea0b4a415ea1e0975c981f95f354de1280d7e7bef3882bf1464b795/Pillow-10.0.1-cp312-cp312-win_amd64.whl.metadata
  Using cached Pillow-10.0.1-cp312-cp312-win_amd64.whl.metadata (9.6 kB)
Using cached munch-4.0.0-py2.py3-none-any.whl (9.9 kB)
Using cached Pillow-10.0.1-cp312-cp312-win_amd64.whl (2.5 MB)
Installing collected packages: pillow, munch, imgui-bundle
Successfully installed imgui-bundle-0.8.8 munch-4.0.0 pillow-10.0.1
```

</p>
</details>

**Comment by pthom** [comment]
> Interestingly, `pip install imgui-bundle` is not checking for PyGLM as a dependency now.

I removed the dependency on PyGLM, since it is only required for one demo. I'll be releasing a new version with Python3.12 support soon.
Thanks!

**Comment by pthom** [comment]
[Version 0.9.0](https://pypi.org/project/imgui-bundle/) now provides support for python 3.12.
