### ISSUE TITLE
I installed the imgui-bundle using 'pip install -v .' with Python 3.10.12, but I'm getting an error when trying to import it.

### ISSUE THREAD

**Issue by iloveyehan** [pthom/imgui_bundle#233]
system:win11
python 3.10
error msg:
append imgui G:\work\001Blender\blender_init\addons\color_picker\extern\imgui_bundle3_10
Traceback (most recent call last):
  File "G:\work\001Blender\stable\blender-4.0.2-windows-x64\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "G:\work\001Blender\stable\blender-4.0.2-windows-x64\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\work\001Blender\blender_init\addons\color_picker\__init__.py", line 5, in <module>
    from .widget import get_wheeL_tri, convert_hsv2rgb32_color3, color_bar, colorpicker, color_palette,picker_switch_button
  File "G:\work\001Blender\blender_init\addons\color_picker\widget.py", line 7, in <module>
    from .extern.imgui_bundle3_10.imgui_bundle import imgui
  File "G:\work\001Blender\blender_init\addons\color_picker\extern\imgui_bundle3_10\imgui_bundle\__init__.py", line 2, in <module>
    from imgui_bundle._imgui_bundle import imgui as imgui  # type: ignore
  File "G:\work\001Blender\blender_init\addons\color_picker\extern\imgui_bundle3_10\imgui_bundle\__init__.py", line 2, in <module>
    from imgui_bundle._imgui_bundle import imgui as imgui  # type: ignore
ImportError: DLL load failed while importing _imgui_bundle: 找不到指定的模块。

**Comment by pthom** [comment]
https://chatgpt.com/share/8d2b41be-786e-4b03-9a62-3cfad88a8b33

**Comment by Roger8** [comment]
@pthom @iloveyehan hi ,I encountered the same problem。How to resolve it ? I can't open the site .

> https://chatgpt.com/share/8d2b41be-786e-4b03-9a62-3cfad88a8b33

**Comment by iloveyehan** [comment]
实际上是缺失了一些动态库文件,查找其他版本的完整文件,复制过来
