### ISSUE TITLE
Can't pip-install requirements-dev.txt

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#51]
I wanted to just see what the generator does (and then possibly work on https://github.com/pthom/imgui_bundle/discussions/38#discussioncomment-4373476), but `pip install -U -r requirements-dev.txt` already fails. I know you're not expecting others to use this yet, but thought i may as well mention it here (though i guess technically what i paste below should be an issue in the litgen repo). This is what i got trying to pip-install:

```
(venv) C:\...\imgui_bundle>pip install -U -r requirements-dev.txt
Collecting litgen@ git+https://github.com/pthom/litgen
  Cloning https://github.com/pthom/litgen to c:\users\huml-dkn\appdata\local\temp\pip-install-sh6uf_z1\litgen_fdb59bc6d2154d2a9479d3c3384255e4
  Running command git clone --filter=blob:none --quiet https://github.com/pthom/litgen 'C:\Users\huml-dkn\AppData\Local\Temp\pip-install-sh6uf_z1\litgen_fdb59bc6d2154d2a9479d3c3384255e4'
  Resolved https://github.com/pthom/litgen to commit 432fb6b424bddf2c5dc838b58cb522226fb45dc0
  Running command git submodule update --init --recursive -q
  error: unable to create file hello_imgui_cmake/android/apkCMake/templates/sdl/gradle_template/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java: Filename too long
  error: unable to create file hello_imgui_cmake/android/apkCMake/templates/sdl/gradle_template/app/src/main/java/org/libsdl/app/HIDDeviceManager.java: Filename too long
  error: unable to create file hello_imgui_cmake/android/apkCMake/templates/sdl/gradle_template/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java: Filename too long
  error: unable to create file hello_imgui_cmake/android/apkCMake/templates/sdl/gradle_template/app/src/main/java/org/libsdl/app/SDLAudioManager.java: Filename too long
  error: unable to create file hello_imgui_cmake/android/apkCMake/templates/sdl/gradle_template/app/src/main/java/org/libsdl/app/SDLControllerManager.java: Filename too long
  From https://github.com/pthom/imgui
   * branch              a08931272922462f8bd4afb52011f8b5bc6a6ebe -> FETCH_HEAD
  Unable to checkout 'c59ba4cf2659648c584dd354ab646811b4cc9aa7' in submodule path 'demos/litgen/imgui_bundle/external/hello_imgui'
  Failed to recurse into submodule path 'demos/litgen/imgui_bundle'
  error: subprocess-exited-with-error

  × git submodule update --init --recursive -q did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```

**Comment by pthom** [comment]
and this is a well known git issue under windows (google git long path)

**Comment by dcnieho** [comment]
Ok, fixed with the first google hit :P. Next one:
```
Collecting litgen@ git+https://github.com/pthom/litgen
  Cloning https://github.com/pthom/litgen to c:\users\huml-dkn\appdata\local\temp\pip-install-6cn54fnu\litgen_7c71d7f44e9f4e37a1a1982ae20fb967
  Running command git clone --filter=blob:none --quiet https://github.com/pthom/litgen 'C:\Users\huml-dkn\AppData\Local\Temp\pip-install-6cn54fnu\litgen_7c71d7f44e9f4e37a1a1982ae20fb967'
  Resolved https://github.com/pthom/litgen to commit 432fb6b424bddf2c5dc838b58cb522226fb45dc0
  Running command git submodule update --init --recursive -q
  From https://github.com/pthom/imgui
   * branch              a08931272922462f8bd4afb52011f8b5bc6a6ebe -> FETCH_HEAD
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package litgen produced metadata for project name srcmlcpp. Fix your #egg=litgen fragments.
Discarding git+https://github.com/pthom/litgen: Requested srcmlcpp from git+https://github.com/pthom/litgen (from -r requirements-dev.txt (line 1)) has inconsistent name: filename has 'litgen', but metadata has 'srcmlcpp'
ERROR: Could not find a version that satisfies the requirement litgen (unavailable) (from versions: none)
ERROR: No matching distribution found for litgen (unavailable)
```

**Comment by dcnieho** [comment]
Hmm, i see that pthom/litgen actually forwards to pthom/srcmlcpp. So i just updated the requirements-dev.txt file.

That gets me to here:
```
Building wheels for collected packages: srcmlcpp, srcml_caller
  Building wheel for srcmlcpp (pyproject.toml) ... done
  Created wheel for srcmlcpp: filename=srcmlcpp-0.1.0-py3-none-any.whl size=613575 sha256=548a49c907bf7d799ce5738b5e8e02cc6b7854e609900f1e11e88cc4bc34d8a4
  Stored in directory: C:\Users\huml-dkn\AppData\Local\Temp\pip-ephem-wheel-cache-yu5eydfe\wheels\4c\fb\21\2cbb57b39f4b643cb14b59b7f54a4519e0e3c381cc4d608eed
  Building wheel for srcml_caller (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for srcml_caller (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [111 lines of output]


      --------------------------------------------------------------------------------
      -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.34.31935.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.34.31935.0
      CMake Warning (dev) at C:/Users/huml-dkn/AppData/Local/Temp/pip-build-env-veuax1i0/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:162 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/huml-dkn/AppData/Local/Temp/pip-build-env-veuax1i0/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeDetermineCXXCompiler.cmake:183 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: C:/Users/huml-dkn/AppData/Local/Temp/pip-install-mycottj2/srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\huml-dkn\AppData\Local\Temp\pip-install-mycottj2\srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7\_skbuild\win-amd64-3.10\cmake-build
        Command:
          cmake 'C:\Users\huml-dkn\AppData\Local\Temp\pip-install-mycottj2\srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\huml-dkn\AppData\Local\Temp\pip-install-mycottj2\srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7\_skbuild\win-amd64-3.10\cmake-install\bindings\srcml_caller' -DPYTHON_VERSION_STRING:STRING=3.10.7 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\huml-dkn\AppData\Local\Temp\pip-build-env-veuax1i0\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv\Scripts\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Program Files\Python310\Include' '-DPYTHON_LIBRARY:PATH=C:\Program Files\Python310\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv\Scripts\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv' '-DPython_INCLUDE_DIR:PATH=C:\Program Files\Python310\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython3_EXECUTABLE:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv\Scripts\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv' '-DPython3_INCLUDE_DIR:PATH=C:\Program Files\Python310\Include' -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is MSVC 19.34.31935.0
      -- The CXX compiler identification is MSVC 19.34.31935.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      'C:/Users/huml-dkn/Desktop/imgui_bundle/venv/Scripts/python.exe' '-c' 'import pybind11; print(pybind11.get_cmake_dir())'
      -- Found PythonInterp: C:/Users/huml-dkn/Desktop/imgui_bundle/venv/Scripts/python.exe (found suitable version "3.10.7", minimum required is "3.6")
      -- Found PythonLibs: C:/Program Files/Python310/libs/python310.lib
      -- Performing Test HAS_MSVC_GL_LTCG
      -- Performing Test HAS_MSVC_GL_LTCG - Success
      -- Found pybind11: C:/Users/huml-dkn/AppData/Local/Temp/pip-build-env-veuax1i0/overlay/Lib/site-packages/pybind11/include (found version "2.10.1")
      -- Project version: 1.0.0
      CMake Error at C:/Users/huml-dkn/AppData/Local/Temp/pip-build-env-veuax1i0/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find LibArchive (missing: LibArchive_LIBRARY
        LibArchive_INCLUDE_DIR) (Required is at least version "3")
      Call Stack (most recent call first):
        C:/Users/huml-dkn/AppData/Local/Temp/pip-build-env-veuax1i0/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        C:/Users/huml-dkn/AppData/Local/Temp/pip-build-env-veuax1i0/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FindLibArchive.cmake:67 (find_package_handle_standard_args)
        external/srcML/src/client/CMakeLists.txt:9 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "C:/Users/huml-dkn/AppData/Local/Temp/pip-install-mycottj2/srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7/_skbuild/win-amd64-3.10/cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "C:\Users\huml-dkn\AppData\Local\Temp\pip-build-env-veuax1i0\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 632, in setup
          env = cmkr.configure(
        File "C:\Users\huml-dkn\AppData\Local\Temp\pip-build-env-veuax1i0\overlay\Lib\site-packages\skbuild\cmaker.py", line 334, in configure
          raise SKBuildError(

      An error occurred while configuring with CMake.
        Command:
          cmake 'C:\Users\huml-dkn\AppData\Local\Temp\pip-install-mycottj2\srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\huml-dkn\AppData\Local\Temp\pip-install-mycottj2\srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7\_skbuild\win-amd64-3.10\cmake-install\bindings\srcml_caller' -DPYTHON_VERSION_STRING:STRING=3.10.7 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\huml-dkn\AppData\Local\Temp\pip-build-env-veuax1i0\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv\Scripts\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Program Files\Python310\Include' '-DPYTHON_LIBRARY:PATH=C:\Program Files\Python310\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv\Scripts\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv' '-DPython_INCLUDE_DIR:PATH=C:\Program Files\Python310\Include' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython3_EXECUTABLE:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv\Scripts\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\huml-dkn\Desktop\imgui_bundle\venv' '-DPython3_INCLUDE_DIR:PATH=C:\Program Files\Python310\Include' -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\huml-dkn\AppData\Local\Temp\pip-install-mycottj2\srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7
        Working directory:
          C:\Users\huml-dkn\AppData\Local\Temp\pip-install-mycottj2\srcml-caller_6ce31932bc6f4d048523b8433c1e7bf7\_skbuild\win-amd64-3.10\cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for srcml_caller
Successfully built srcmlcpp
Failed to build srcml_caller
ERROR: Could not build wheels for srcml_caller, which is required to install pyproject.toml-based projects
```

I see libarchive can be downloaded [here](https://github.com/libarchive/libarchive/releases/tag/v3.6.2), but where do i place it for CMake to find it?
